// Type definitions for extending Express objects

declare global {
  namespace Express {
    interface Request {
      /**
       * Unique request ID generated by requestIdMiddleware
       */
      id?: string;
      
      /**
       * Authenticated user object (set by authenticate middleware)
       */
      user?: {
        userId: string;
        email: string;
        username: string;
        role: string;
      };
      
      /**
       * Request ID for backward compatibility
       * @deprecated Use `id` instead
       */
      requestId?: string;
    }
    
    interface Response {
      /**
       * Response locals for request-specific data
       */
      locals: Record<string, any>;
    }
  }
}

// This file doesn't export anything, it just augments global types
export {};